// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT.
// Server-only subset of src/data/cards.ts (just the colour token map the
// engine + rotation modules read).
import type { CreatorTypeName as CreatorType } from "./gameCards.ts";
export const CREATOR_TYPE_COLORS: Record<CreatorType, string> = {
  Lava: "#da7028", Fire: "#eda35e", Whirlwind: "#abd49e", Snow: "#c2e5cf",
  Lightning: "#8fd4b8", Sun: "#f2d178", Lake: "#7db2d9", Ocean: "#6173b0",
  Tree: "#db7d75", Mountain: "#c45463", Soil: "#944a47", River: "#99ccd4",
  Sky: "#bdb2e5",
};
