// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT.
// Mirror of src/lib/game/elements.ts. Edit the source file, then re-run the script.
import type { CreatorTypeName } from "./gameCards.ts";

/** The four classical elements that form the centre of an ecosystem. */
export type Element = "Earth" | "Fire" | "Air" | "Water";

/** Maps each of the 13 Creator Types to one of the 4 elements (Sky is its own wildcard). */
export const TYPE_TO_ELEMENT: Record<CreatorTypeName, Element | "Sky"> = {
  Lava: "Fire",
  Fire: "Fire",
  Sun: "Fire",
  Whirlwind: "Air",
  Lightning: "Air",
  Snow: "Air",
  Lake: "Water",
  Ocean: "Water",
  River: "Water",
  Tree: "Earth",
  Mountain: "Earth",
  Soil: "Earth",
  Sky: "Sky",
};

// Element colours are aligned to the canonical Creator Type palette
// (spreadsheet hexes) so element Creator cards visually match the
// corresponding animal half-hexes on the board.
//  Fire  → Fire creator type   (#eda35e)
//  Air   → Whirlwind            (#abd49e)
//  Water → Ocean                (#6173b0)
//  Earth → Soil                 (#944a47)
//  Sky   → Sky                  (#bdb2e5)
export const ELEMENT_COLORS: Record<Element | "Sky", string> = {
  Earth: "#944a47",
  Fire: "#eda35e",
  Air: "#abd49e",
  Water: "#6173b0",
  Sky: "#bdb2e5",
};

export const ELEMENTS: Element[] = ["Earth", "Fire", "Air", "Water"];
