// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT.
// Server-only subset of src/lib/gameCards.ts (types + GameCard shape).
export type CreatorTypeName =
  | "Lava" | "Fire" | "Whirlwind" | "Snow" | "Lightning" | "Sun"
  | "Lake" | "Ocean" | "Tree" | "Mountain" | "Soil" | "River" | "Sky";
export interface GameCard {
  id: string;
  slug: string;
  name: string;
  type_a: CreatorTypeName;
  type_b: CreatorTypeName;
  types: [CreatorTypeName, CreatorTypeName];
  code: string | null;
  mythical: boolean;
  descriptor: string | null;
  art_path: string | null;
  art_url: string | null;
  sort_order: number;
}
