// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT.
// Mirror of src/lib/game/types.ts. Edit the source file, then re-run the script.
/**
 * Core types for the BCreators ecosystem-building card game.
 *
 * Each player builds their OWN honeycomb ecosystem of 16 cards:
 *   - 4 Creator Cards (one of each element: Earth / Fire / Air / Water,
 *     with Sky Creator able to substitute for any element)
 *   - 12 Animal Cards (3 matching each Creator, by shared Creator Type;
 *     Golden Body substitutes for any animal)
 *
 * Coordinates are axial (q,r) on a pointy-top hex grid.
 */

import type { CreatorTypeName, GameCard } from "./gameCards.ts";
import type { Element } from "./elements.ts";

export type Axial = { q: number; r: number };

export type CardKind =
  | "animal"        // standard animal, 1 or 2 Creator Types
  | "creator"       // Earth / Fire / Air / Water creator card
  | "sky_creator"   // wildcard creator — counts as any element
  | "sky_creature"  // mythical animal — also playable as a STEALER
  | "golden_body"   // wildcard animal
  | "golden_hive";  // blocks one disaster

/** A single physical copy of a card in the deck / hand / ecosystem. */
export interface DeckCard {
  /** Unique-per-copy id (e.g. "fox#1"). */
  uid: string;
  kind: CardKind;
  name: string;
  /** For animals / sky_creatures — the Creator Types they belong to (1-2). */
  types?: CreatorTypeName[];
  /** For animals / sky_creatures — the underlying art / descriptor. */
  source?: GameCard;
  /** For 'creator' cards — the element they represent. */
  element?: Element;
  /** For 'creator' cards — the specific Creator Type displayed (e.g. "Snow"). */
  displayType?: CreatorTypeName;
  /** True if this is a mythical / golden / sky variant (for badge styling). */
  special?: boolean;
  /** Marks a Golden Hive that has already been used to block a disaster —
   *  it sits on the used pile but can never be picked up again. */
  spent?: boolean;
  /** True if this card was picked up from the used pile on the CURRENT turn.
   *  Such a card cannot be re-weaponised as a Disaster the same turn — it must
   *  be placed on the board this turn or held until next turn. Cleared in
   *  advanceTurn. Prevents infinite Creator→Disaster recycling. */
  pickedUpThisTurn?: boolean;
  /** True once this Creator copy has been played as a Disaster. It may still
   *  be picked up from the used pile and placed on a board, but it can never
   *  be played as a Disaster again. Persists for the rest of the match. */
  disasterSpent?: boolean;
}

export interface PlacedCard {
  card: DeckCard;
  pos: Axial;
  /** 0..5 — number of 60° clockwise rotations applied to the hex background.
   *  Only affects two-colour split cards (animals / sky_creatures). The
   *  artwork itself always stays upright. */
  rotation?: number;
}

export interface Ecosystem {
  /** Placed cards keyed by "q,r". */
  placed: Map<string, PlacedCard>;
}

export type PlayerStatus = "active" | "finalised" | "forfeit" | "conceded";

export interface PlayerState {
  id: string;
  name: string;
  hand: DeckCard[];
  ecosystem: Ecosystem;
  /** Active hive shield (true after picking up / playing a hive proactively). */
  hiveShield: boolean;
  /** Cumulative gameplay score for end-of-match display. */
  score: number;
  /** True once the player has done their opening 5-card pick-up. Before then
   *  the only legal pick-up action is `drawInitialFive`. */
  firstPickupDone?: boolean;
  /** A.2 — final placement (1 = winner, N = last). Null until finalised. */
  rank?: number | null;
  /** A.2 — lifecycle status. 'active' is the default; once finalised /
   *  forfeited / conceded the player's turns are skipped. */
  status?: PlayerStatus;
  /** A.2 — epoch ms when this player was finalised. */
  finalisedAt?: number | null;
}

export type TurnPhase = "draw" | "place";

/** Game mode controlling the end-condition. */
export type GameMode =
  | "end_of_days"   // classic: first to assemble full ecosystem
  | "first_to_50"   // first player to reach a target total score wins
  | "beat_clock";   // overall match timer + per-turn timer; high score wins on time-up

export interface GameConfig {
  /** For first_to_50: points threshold. Default 50. */
  targetScore?: number;
  /** For beat_clock: epoch ms when the match auto-ends. */
  matchEndsAt?: number;
  /** For beat_clock: total match length in minutes (for display at game-end). */
  matchMinutes?: number;
  /** For beat_clock: seconds allowed per turn before auto-end-turn. */
  turnSeconds?: number;
}

/** A disaster waiting on the (at most one) Hive-holding victim's decision
 *  before it resolves.
 *
 *  IMPORTANT — single-Hive invariant: the deck contains exactly ONE Golden
 *  Hive card across the entire game (this does not scale with player
 *  count). Therefore at any moment at most one player can hold an unspent
 *  Hive, and `victimIds.length` is ALWAYS ≤ 1 in real play (0 when no
 *  opponent holds the Hive, 1 when exactly one does). The array machinery
 *  is retained for structural clarity — `resolveDisaster` shifts the head
 *  off the queue and the wipe applies to every non-blocking opponent — but
 *  it must NOT be read as evidence the engine supports multiple Hives. It
 *  does not. If you find yourself constructing a state with two
 *  Hive-holders, that state is unreachable from any legal play sequence.
 */
export interface PendingDisaster {
  attackerId: string;
  /** The single Hive-holding victim still to decide, wrapped in an array
   *  for queue-shape consistency. Length is 0 or 1 — never more (see
   *  single-Hive invariant above). */
  victimIds: string[];
  /** Backwards-compat alias for `victimIds[0]`. New code should prefer
   *  `victimIds`; this field is kept so existing 2-player call sites
   *  (apply-move, Play.tsx, useBeatTheClockTimer) continue to compile. */
  victimId: string;
  /** Player IDs that have already chosen "Activate Now" — they are exempted
   *  from the wipe when it finally resolves. */
  blockedBy?: string[];
  creator: DeckCard;
}


export interface MatchState {
  players: PlayerState[];
  turn: number;
  draw: DeckCard[];
  used: DeckCard[];
  phase: TurnPhase;
  drawnThisTurn: number;
  placedThisTurn: number;
  turnNumber: number;
  finished: boolean;
  /** Backwards-compat: equals `placements[0]?.playerId` once finalised.
   *  `placements` is the source of truth for N-player matches. */
  winnerId: string | null;
  lastEvent?: string;
  pendingDisaster?: PendingDisaster | null;
  /** Game mode + config. Older saves omit these → treated as end_of_days. */
  gameMode?: GameMode;
  gameConfig?: GameConfig;
  /** A.2 — final ranked placements for the match. Populated as each player
   *  is finalised; ordered by rank ascending (rank 1 first). For a 2-player
   *  match this has exactly two entries. */
  placements?: Array<{ playerId: string; rank: number }>;
  /** A.2 — turn rotation indices into `players`. If absent the engine uses
   *  `[0, 1, …, N-1]`. A.3/B will populate this with a randomised
   *  permutation; A.2 just reads it. */
  turnOrder?: number[];
}

/** Total score used for First-to-50 / Beat-the-Clock leaderboards.
 *  Mirrors the running pts shown in ScorePanel (ecosystem.placed.size * 2)
 *  plus engine-tracked bonus points (disaster wipes, etc.). */
export function playerTotalScore(player: PlayerState): number {
  return player.ecosystem.placed.size * 2 + (player.score ?? 0);
}

export const HAND_SIZE = 5;
/** Maximum cards a player may hold AFTER their turn. Per the rule book a
 *  player draws 2 and places 2 every turn, so their hand never exceeds 5
 *  at end-of-turn. Disasters may temporarily push the hand above this
 *  (no cards are lost), and the holder must play / discard down before
 *  drawing again. */
export const HAND_LIMIT = 5;
export const ECOSYSTEM_TARGET = 16; // 4 creators + 12 animals
export const CREATORS_NEEDED = 4;
export const ANIMALS_PER_CREATOR = 3;
