#!/usr/bin/env bash
#
# Mirrors src/lib/game/{types,board,elements,rotation,engine}.ts into
# supabase/functions/_shared/game/ so the apply-move edge function can reuse
# the exact same game rules as the client. Run by CI to detect drift.
#
# Why this exists: Supabase edge functions can only import from their own
# directory or from supabase/functions/_shared/. They cannot reach back into
# src/. We avoid a forked engine by mirroring + a tiny import rewrite so the
# files compile under Deno without pulling in client-only deps (assets,
# Supabase client, etc.).
#
# Usage:  scripts/sync-game-engine.sh                # write mirror
#         scripts/sync-game-engine.sh --check        # exit 1 if mirror is stale
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src/lib/game"
DEST="$ROOT/supabase/functions/_shared/game"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP"

# --- stub modules (replace @/-prefixed client-only imports) ----------------
cat > "$TMP/gameCards.ts" <<'TS'
// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT.
// Server-only subset of src/lib/gameCards.ts (types + GameCard shape).
export type CreatorTypeName =
  | "Lava" | "Fire" | "Whirlwind" | "Snow" | "Lightning" | "Sun"
  | "Lake" | "Ocean" | "Tree" | "Mountain" | "Soil" | "River" | "Sky";
export interface GameCard {
  id: string;
  slug: string;
  name: string;
  type_a: CreatorTypeName;
  type_b: CreatorTypeName;
  types: [CreatorTypeName, CreatorTypeName];
  code: string | null;
  mythical: boolean;
  descriptor: string | null;
  art_path: string | null;
  art_url: string | null;
  sort_order: number;
}
TS

cat > "$TMP/cards.ts" <<'TS'
// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT.
// Server-only subset of src/data/cards.ts (just the colour token map the
// engine + rotation modules read).
import type { CreatorTypeName as CreatorType } from "./gameCards.ts";
export const CREATOR_TYPE_COLORS: Record<CreatorType, string> = {
  Lava: "#da7028", Fire: "#eda35e", Whirlwind: "#abd49e", Snow: "#c2e5cf",
  Lightning: "#8fd4b8", Sun: "#f2d178", Lake: "#7db2d9", Ocean: "#6173b0",
  Tree: "#db7d75", Mountain: "#c45463", Soil: "#944a47", River: "#99ccd4",
  Sky: "#bdb2e5",
};
TS

# --- mirror engine modules with import rewrites -----------------------------
mirror() {
  local name="$1"
  local in="$SRC/$name"
  local out="$TMP/$name"
  {
    echo "// GENERATED by scripts/sync-game-engine.sh — DO NOT EDIT."
    echo "// Mirror of src/lib/game/$name. Edit the source file, then re-run the script."
    # Rewrite client-only imports to server-safe stubs. Add explicit .ts so
    # Deno is happy without an import_map.
    sed \
      -e 's|from "@/lib/gameCards"|from "./gameCards.ts"|g' \
      -e 's|from "@/data/cards"|from "./cards.ts"|g' \
      -e 's|from "\./types"|from "./types.ts"|g' \
      -e 's|from "\./board"|from "./board.ts"|g' \
      -e 's|from "\./elements"|from "./elements.ts"|g' \
      -e 's|from "\./rotation"|from "./rotation.ts"|g' \
      -e 's|import("\./types")|import("./types.ts")|g' \
      -e 's|import("\./board")|import("./board.ts")|g' \
      -e 's|import("\./elements")|import("./elements.ts")|g' \
      -e 's|import("\./rotation")|import("./rotation.ts")|g' \
      "$in"
  } > "$out"
}

mirror types.ts
mirror board.ts
mirror elements.ts
mirror rotation.ts
mirror engine.ts

if [ "${1:-}" = "--check" ]; then
  if ! diff -ruN "$DEST" "$TMP" >/dev/null 2>&1; then
    echo "::error::supabase/functions/_shared/game is out of sync with src/lib/game" >&2
    diff -ruN "$DEST" "$TMP" || true
    exit 1
  fi
  echo "game engine mirror is up to date."
  exit 0
fi

rm -rf "$DEST"
mkdir -p "$DEST"
cp "$TMP"/*.ts "$DEST/"
echo "synced shared game engine → $DEST"
