UPDATE public.game_cards SET descriptor = v.descriptor FROM (VALUES
('unicorn', E'Through crystal clouds I leave no trace,\nA whispered dream in boundless space'),
('flying-fox', E'At dusk I rise through amber skies,\nA shadow crowned with living fire'),
('crane', E'I stand where stillness learns to break,\nA flash of sky upon the lake'),
('swordfish', E'I split the tides with silver flame,\nA storm beneath without a name'),
('giraffe', E'Above the leaves my silence bends,\nWhere sky and branch together blend'),
('falcon', E'I fall like thunder from the heights,\nA sharpened shadow born for flight'),
('platypus', E'Beneath the mud strange currents sleep,\nAnd secret rivers run too deep'),
('catfish', E'I stir the dark where waters hum,\nA hidden spark where currents run'),
('thunderbird', E'I break the clouds with blazing cries,\nThe storm itself beneath my wings'),
('turtle', E'I drift through warmth and mirrored glow,\nWhere quiet ancient waters flow'),
('starfish', E'I hold the sunlight in the sea,\nA glowing hand beneath the deep'),
('koala', E'Among the leaves I dream and sway,\nA golden hush through heat of day'),
('lion', E'Upon the stones my silence reigns,\nA steady fire through wind and rain'),
('elephant', E'I walk the earth with ancient grace,\nAnd carry dawn in every place'),
('kingfisher', E'I flash like jewels through silver streams,\nA fleeting spark of water dreams'),
('rainbow-serpent', E'I curve through heavens bright and vast,\nA living bridge of light and past'),
('jellyfish', E'I bloom beneath the mirrored deep,\nA drifting dream the waters keep'),
('frog', E'I sing where roots and waters meet,\nA green pulse in the evening heat'),
('crab', E'Along the stones I carve my way,\nWith tidal patience old as clay'),
('wombat', E'I burrow deep where waters rest,\nA quiet keeper of the earth'),
('beaver', E'I shape the flow with tooth and will,\nA builder where the streams grow still'),
('bunyip', E'I leap through mist and morning blue,\nA fleeting wish the dawn once knew'),
('seahorse', E'Through swaying forests soft I roam,\nA tiny guardian of the foam'),
('crocodile', E'I wait where ancient rivers end,\nA stone alive beneath the wind'),
('whale', E'My songs move deep through darkened earth,\nOld as the tides that gave me birth'),
('stingray', E'I glide where shifting currents weave,\nA shadow soft as falling leaves'),
('merper', E'Between the stars and tides I sing,\nA silver dream on hidden wings'),
('cassowary', E'Through jungle ash my footsteps fall,\nA forest flame both fierce and tall'),
('goat', E'Along the cliffs my sure feet climb,\nWhere roots and stone outlast all time'),
('sloth', E'I move as softly as the moss,\nA patient soul untouched by loss'),
('snake', E'Through tangled roots I slide unseen,\nA whisper hidden deep in green'),
('knome', E'I guard the places few can find,\nWhere branch and cloud together bind'),
('tiger', E'Within the peaks old embers roar,\nA striped flame behind stone doors'),
('leopard', E'I vanish where the cold winds creep,\nA ghost the frozen summits keep'),
('bison', E'I move like thunder through the earth,\nA grounded force of patient worth'),
('salamander', E'Through hidden streams and warming stone,\nI carry secrets all my own'),
('bigfoot', E'Beyond the mist my footsteps fade,\nA legend wandering light and shade'),
('anteater', E'Along the banks I search and roam,\nA quiet pilgrim far from home'),
('hobbit', E'Beneath green hills my lantern glows,\nWhere simple joys and wonder grow'),
('seamonster', E'Between river song and starlit sky,\nI weave the secrets tides imply')
) AS v(slug, descriptor) WHERE public.game_cards.slug = v.slug;