UPDATE public.game_cards SET descriptor = v.descriptor FROM (VALUES
('fox', E'Through ember dusk with silent feet,\nI guard the place where wild hearts meet'),
('bee', E'With frozen wings through ash I roam,\nA spark that hums where none call home'),
('wolf', E'Beneath cold moons my embers glow,\nI sing of fires buried in snow'),
('wasp', E'I strike before the thunder speaks,\nA molten spark with gilded wings'),
('iguana', E'Upon warm stone I dream in flame,\nStill as dawn yet never tame'),
('echidna', E'I wear the earth like ancient mail,\nAnd hide my storms beneath still trails'),
('octopus', E'From blackened depths my secrets creep,\nWhere fire and tide together sleep'),
('bear', E'Within my chest the mountains turn,\nSoft roots below, above me burn'),
('eel', E'Through molten currents swift I glide,\nA ribbon forged by fire and tide'),
('griffin', E'With ash and wind beneath my wings,\nI guard the silence stormlight brings'),
('squirrel', E'I scatter sparks from tree to tree,\nA laughing flame no hand can keep'),
('mouse', E'A tiny ember softly glows,\nAgainst the hush of drifting snow'),
('cheetah', E'I race the storm on burning ground,\nBefore the thunder makes a sound'),
('zebra', E'I run where golden mirrors blaze,\nBetween the lines of night and day'),
('panda', E'Beneath calm waters embers hide,\nWarm lantern eyes in moonlit tides'),
('seal', E'I dance where foam and fire entwine,\nA fleeting spark on ancient tides'),
('lemur', E'Through tangled limbs I leap unseen,\nA lantern spirit dressed in green'),
('gorilla', E'I stand where ancient echoes sleep,\nA quiet flame the stones still keep'),
('camel', E'Across the dunes my fire survives,\nA patient spark where silence thrives'),
('otter', E'I spin through silver streams at play,\nAnd carry sparks that never stay'),
('dragon', E'On crimson winds my shadow flies,\nA blazing secret in the skies'),
('arctic-hare', E'I vanish where the white winds race,\nA fleeting whisper without trace'),
('firefly', E'I flicker bright before the storm,\nA tiny pulse in shifting form'),
('kangaroo', E'Across wide plains I bound with light,\nA golden rhythm born of flight'),
('dragonfly', E'Above still waters thin wings glide,\nTracing circles the reeds can''t hide'),
('dolphin', E'I ride the breath of roaring seas,\nA laughing wave upon the breeze'),
('woodpecker', E'I drum the winds through bark and bone,\nAwakening songs the woods have known'),
('horse', E'I carry storms through stone and snow,\nWhere ancient paths still rise and go'),
('ostrich', E'Across red earth swift shadows run,\nChasing the breath of fading sun'),
('shark', E'I turn where restless waters bend,\nA silent force with neither end'),
('fairy', E'I drift between the dusk and dawn,\nA silver sigh before I''m gone'),
('rabbit', E'I leap through veils of drifting white,\nA fleeting shape in moonlit flight'),
('deer', E'With antlers bright as frozen stars,\nI run where silent thunder scars'),
('peacock', E'I wear the dawn in jeweled light,\nA winter crown of burning white'),
('swan', E'Upon still glass I softly glide,\nWhere moon and memory coincide'),
('penguin', E'Through frozen tides my heart beats strong,\nA steadfast soul where ice belongs'),
('spider', E'I weave pale lace through winter air,\nA silver secret hanging there'),
('snow-leopard', E'Among the peaks no shadow stays,\nI walk unseen through endless haze'),
('alpaca', E'On gentle hills my silence grows,\nSoft as the earth beneath the snows'),
('duck', E'I drift where quiet currents roam,\nA feathered thought far from home')
) AS v(slug, descriptor) WHERE public.game_cards.slug = v.slug;