// AUTO-GENERATED by scripts/gen-quiz-bank.py — do not hand-edit.
// Multiple-choice question bank for the Creator Types learning layer.
// Regenerate with: python scripts/gen-quiz-bank.py

export type QuizStyle =
  | 'family_recall' | 'element_recall' | 'team_role_recall'
  | 'reverse_family_role'
  | 'signature_whoami' | 'shadow_whoami' | 'at_table_whoami' | 'ymbi_whoami'
  | 'compare_family' | 'compare_element'
  | 'not_family' | 'not_element'
  | 'animal_type' | 'not_animal_type' | 'animal_has_type';

export type QuizCategory =
  | 'family' | 'element' | 'team_role' | 'reverse'
  | 'signature' | 'shadow' | 'at_table' | 'ymbi'
  | 'compare' | 'exclusion' | 'animals';

export interface QuizQuestion {
  id: string;
  prompt: string;
  options: string[];          // always 4
  correct_index: number;      // 0..3
  explanation: string;        // one-line teaching moment
  style: QuizStyle;
  category: QuizCategory;
  creator: string | null;     // subject Creator when scoped to one
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    "id": "q0001",
    "prompt": "Fire Creator is part of which Family?",
    "options": [
      "Optimists",
      "Catalysts",
      "Humanists",
      "Sustainers"
    ],
    "correct_index": 1,
    "explanation": "Fire belongs to the Catalysts family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Fire"
  },
  {
    "id": "q0002",
    "prompt": "Lake Creator is part of which Family?",
    "options": [
      "Realists",
      "Catalysts",
      "Humanists",
      "Sustainers"
    ],
    "correct_index": 2,
    "explanation": "Lake belongs to the Humanists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Lake"
  },
  {
    "id": "q0003",
    "prompt": "Lava Creator is part of which Family?",
    "options": [
      "Humanists",
      "Catalysts",
      "Optimists",
      "Sustainers"
    ],
    "correct_index": 1,
    "explanation": "Lava belongs to the Catalysts family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Lava"
  },
  {
    "id": "q0004",
    "prompt": "Lightning Creator is part of which Family?",
    "options": [
      "Optimists",
      "Catalysts",
      "Humanists",
      "Sustainers"
    ],
    "correct_index": 0,
    "explanation": "Lightning belongs to the Optimists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Lightning"
  },
  {
    "id": "q0005",
    "prompt": "Mountain Creator is part of which Family?",
    "options": [
      "Realists",
      "Optimists",
      "Sustainers",
      "Catalysts"
    ],
    "correct_index": 0,
    "explanation": "Mountain belongs to the Realists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Mountain"
  },
  {
    "id": "q0006",
    "prompt": "Ocean Creator is part of which Family?",
    "options": [
      "Optimists",
      "Sustainers",
      "Catalysts",
      "Humanists"
    ],
    "correct_index": 3,
    "explanation": "Ocean belongs to the Humanists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Ocean"
  },
  {
    "id": "q0007",
    "prompt": "River Creator is part of which Family?",
    "options": [
      "Realists",
      "Humanists",
      "Catalysts",
      "Optimists"
    ],
    "correct_index": 0,
    "explanation": "River belongs to the Realists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "River"
  },
  {
    "id": "q0008",
    "prompt": "Sky Creator is part of which Family?",
    "options": [
      "Sustainers",
      "Realists",
      "Catalysts",
      "Optimists"
    ],
    "correct_index": 0,
    "explanation": "Sky belongs to the Sustainers family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Sky"
  },
  {
    "id": "q0009",
    "prompt": "Snow Creator is part of which Family?",
    "options": [
      "Optimists",
      "Catalysts",
      "Humanists",
      "Sustainers"
    ],
    "correct_index": 0,
    "explanation": "Snow belongs to the Optimists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Snow"
  },
  {
    "id": "q0010",
    "prompt": "Soil Creator is part of which Family?",
    "options": [
      "Catalysts",
      "Realists",
      "Humanists",
      "Optimists"
    ],
    "correct_index": 1,
    "explanation": "Soil belongs to the Realists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Soil"
  },
  {
    "id": "q0011",
    "prompt": "Sun Creator is part of which Family?",
    "options": [
      "Sustainers",
      "Realists",
      "Optimists",
      "Catalysts"
    ],
    "correct_index": 2,
    "explanation": "Sun belongs to the Optimists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Sun"
  },
  {
    "id": "q0012",
    "prompt": "Tree Creator is part of which Family?",
    "options": [
      "Realists",
      "Catalysts",
      "Humanists",
      "Optimists"
    ],
    "correct_index": 2,
    "explanation": "Tree belongs to the Humanists family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Tree"
  },
  {
    "id": "q0013",
    "prompt": "Whirlwind Creator is part of which Family?",
    "options": [
      "Sustainers",
      "Humanists",
      "Catalysts",
      "Realists"
    ],
    "correct_index": 2,
    "explanation": "Whirlwind belongs to the Catalysts family.",
    "style": "family_recall",
    "category": "family",
    "creator": "Whirlwind"
  },
  {
    "id": "q0014",
    "prompt": "Which element governs the Fire Creator?",
    "options": [
      "Water",
      "Air",
      "Fire",
      "Earth"
    ],
    "correct_index": 2,
    "explanation": "Fire is an Fire type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Fire"
  },
  {
    "id": "q0015",
    "prompt": "Which element governs the Lake Creator?",
    "options": [
      "Water",
      "Fire",
      "Air",
      "Earth"
    ],
    "correct_index": 0,
    "explanation": "Lake is an Water type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Lake"
  },
  {
    "id": "q0016",
    "prompt": "Which element governs the Lava Creator?",
    "options": [
      "Air",
      "Water",
      "Earth",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "Lava is an Fire type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Lava"
  },
  {
    "id": "q0017",
    "prompt": "Which element governs the Lightning Creator?",
    "options": [
      "Earth",
      "Fire",
      "Air",
      "Water"
    ],
    "correct_index": 2,
    "explanation": "Lightning is an Air type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Lightning"
  },
  {
    "id": "q0018",
    "prompt": "Which element governs the Mountain Creator?",
    "options": [
      "Water",
      "Air",
      "Fire",
      "Earth"
    ],
    "correct_index": 3,
    "explanation": "Mountain is an Earth type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Mountain"
  },
  {
    "id": "q0019",
    "prompt": "Which element governs the Ocean Creator?",
    "options": [
      "Air",
      "Earth",
      "Fire",
      "Water"
    ],
    "correct_index": 3,
    "explanation": "Ocean is an Water type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Ocean"
  },
  {
    "id": "q0020",
    "prompt": "Which element governs the River Creator?",
    "options": [
      "Air",
      "Earth",
      "Fire",
      "Water"
    ],
    "correct_index": 3,
    "explanation": "River is an Water type.",
    "style": "element_recall",
    "category": "element",
    "creator": "River"
  },
  {
    "id": "q0021",
    "prompt": "Which element governs the Sky Creator?",
    "options": [
      "Air",
      "Water",
      "Earth",
      "Fire"
    ],
    "correct_index": 0,
    "explanation": "Sky is an Air type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Sky"
  },
  {
    "id": "q0022",
    "prompt": "Which element governs the Snow Creator?",
    "options": [
      "Earth",
      "Air",
      "Fire",
      "Water"
    ],
    "correct_index": 1,
    "explanation": "Snow is an Air type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Snow"
  },
  {
    "id": "q0023",
    "prompt": "Which element governs the Soil Creator?",
    "options": [
      "Fire",
      "Earth",
      "Water",
      "Air"
    ],
    "correct_index": 1,
    "explanation": "Soil is an Earth type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Soil"
  },
  {
    "id": "q0024",
    "prompt": "Which element governs the Sun Creator?",
    "options": [
      "Water",
      "Fire",
      "Air",
      "Earth"
    ],
    "correct_index": 1,
    "explanation": "Sun is an Fire type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Sun"
  },
  {
    "id": "q0025",
    "prompt": "Which element governs the Tree Creator?",
    "options": [
      "Water",
      "Earth",
      "Fire",
      "Air"
    ],
    "correct_index": 1,
    "explanation": "Tree is an Earth type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Tree"
  },
  {
    "id": "q0026",
    "prompt": "Which element governs the Whirlwind Creator?",
    "options": [
      "Water",
      "Air",
      "Fire",
      "Earth"
    ],
    "correct_index": 1,
    "explanation": "Whirlwind is an Air type.",
    "style": "element_recall",
    "category": "element",
    "creator": "Whirlwind"
  },
  {
    "id": "q0027",
    "prompt": "What team role does the Fire Creator play?",
    "options": [
      "Integrator",
      "Director",
      "Stabilizer",
      "The Visionary"
    ],
    "correct_index": 2,
    "explanation": "Fire operates as a Stabilizer.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Fire"
  },
  {
    "id": "q0028",
    "prompt": "What team role does the Lake Creator play?",
    "options": [
      "Director",
      "Stabilizer",
      "The Visionary",
      "Integrator"
    ],
    "correct_index": 0,
    "explanation": "Lake operates as a Director.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Lake"
  },
  {
    "id": "q0029",
    "prompt": "What team role does the Lava Creator play?",
    "options": [
      "Stabilizer",
      "Integrator",
      "The Visionary",
      "Director"
    ],
    "correct_index": 3,
    "explanation": "Lava operates as a Director.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Lava"
  },
  {
    "id": "q0030",
    "prompt": "What team role does the Lightning Creator play?",
    "options": [
      "Stabilizer",
      "Integrator",
      "The Visionary",
      "Director"
    ],
    "correct_index": 0,
    "explanation": "Lightning operates as a Stabilizer.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Lightning"
  },
  {
    "id": "q0031",
    "prompt": "What team role does the Mountain Creator play?",
    "options": [
      "The Visionary",
      "Integrator",
      "Director",
      "Stabilizer"
    ],
    "correct_index": 2,
    "explanation": "Mountain operates as a Director.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Mountain"
  },
  {
    "id": "q0032",
    "prompt": "What team role does the Ocean Creator play?",
    "options": [
      "The Visionary",
      "Integrator",
      "Stabilizer",
      "Director"
    ],
    "correct_index": 2,
    "explanation": "Ocean operates as a Stabilizer.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Ocean"
  },
  {
    "id": "q0033",
    "prompt": "What team role does the River Creator play?",
    "options": [
      "Stabilizer",
      "Director",
      "Integrator",
      "The Visionary"
    ],
    "correct_index": 2,
    "explanation": "River operates as a Integrator.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "River"
  },
  {
    "id": "q0034",
    "prompt": "What team role does the Sky Creator play?",
    "options": [
      "Integrator",
      "Director",
      "The Visionary",
      "Stabilizer"
    ],
    "correct_index": 2,
    "explanation": "Sky operates as a The Visionary.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Sky"
  },
  {
    "id": "q0035",
    "prompt": "What team role does the Snow Creator play?",
    "options": [
      "Director",
      "Integrator",
      "Stabilizer",
      "The Visionary"
    ],
    "correct_index": 0,
    "explanation": "Snow operates as a Director.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Snow"
  },
  {
    "id": "q0036",
    "prompt": "What team role does the Soil Creator play?",
    "options": [
      "The Visionary",
      "Integrator",
      "Director",
      "Stabilizer"
    ],
    "correct_index": 3,
    "explanation": "Soil operates as a Stabilizer.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Soil"
  },
  {
    "id": "q0037",
    "prompt": "What team role does the Sun Creator play?",
    "options": [
      "Stabilizer",
      "Director",
      "Integrator",
      "The Visionary"
    ],
    "correct_index": 2,
    "explanation": "Sun operates as a Integrator.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Sun"
  },
  {
    "id": "q0038",
    "prompt": "What team role does the Tree Creator play?",
    "options": [
      "The Visionary",
      "Director",
      "Integrator",
      "Stabilizer"
    ],
    "correct_index": 2,
    "explanation": "Tree operates as a Integrator.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Tree"
  },
  {
    "id": "q0039",
    "prompt": "What team role does the Whirlwind Creator play?",
    "options": [
      "Stabilizer",
      "Integrator",
      "The Visionary",
      "Director"
    ],
    "correct_index": 1,
    "explanation": "Whirlwind operates as a Integrator.",
    "style": "team_role_recall",
    "category": "team_role",
    "creator": "Whirlwind"
  },
  {
    "id": "q0040",
    "prompt": "Which Creator is the Catalysts Stabilizer?",
    "options": [
      "Sky",
      "Lightning",
      "River",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "Fire is the Catalysts Stabilizer.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Fire"
  },
  {
    "id": "q0041",
    "prompt": "Which Creator is the Humanists Director?",
    "options": [
      "Mountain",
      "Sun",
      "Fire",
      "Lake"
    ],
    "correct_index": 3,
    "explanation": "Lake is the Humanists Director.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Lake"
  },
  {
    "id": "q0042",
    "prompt": "Which Creator is the Catalysts Director?",
    "options": [
      "Snow",
      "Sun",
      "River",
      "Lava"
    ],
    "correct_index": 3,
    "explanation": "Lava is the Catalysts Director.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Lava"
  },
  {
    "id": "q0043",
    "prompt": "Which Creator is the Optimists Stabilizer?",
    "options": [
      "Whirlwind",
      "Soil",
      "Fire",
      "Lightning"
    ],
    "correct_index": 3,
    "explanation": "Lightning is the Optimists Stabilizer.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Lightning"
  },
  {
    "id": "q0044",
    "prompt": "Which Creator is the Realists Director?",
    "options": [
      "Mountain",
      "Lava",
      "Fire",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "Mountain is the Realists Director.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Mountain"
  },
  {
    "id": "q0045",
    "prompt": "Which Creator is the Humanists Stabilizer?",
    "options": [
      "Tree",
      "River",
      "Lava",
      "Ocean"
    ],
    "correct_index": 3,
    "explanation": "Ocean is the Humanists Stabilizer.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Ocean"
  },
  {
    "id": "q0046",
    "prompt": "Which Creator is the Realists Integrator?",
    "options": [
      "Whirlwind",
      "River",
      "Lava",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "River is the Realists Integrator.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "River"
  },
  {
    "id": "q0047",
    "prompt": "Which Creator is the Sustainers The Visionary?",
    "options": [
      "Ocean",
      "Lava",
      "Sun",
      "Sky"
    ],
    "correct_index": 3,
    "explanation": "Sky is the Sustainers The Visionary.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Sky"
  },
  {
    "id": "q0048",
    "prompt": "Which Creator is the Optimists Director?",
    "options": [
      "Sun",
      "Snow",
      "Lava",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "Snow is the Optimists Director.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Snow"
  },
  {
    "id": "q0049",
    "prompt": "Which Creator is the Realists Stabilizer?",
    "options": [
      "Sun",
      "Fire",
      "River",
      "Soil"
    ],
    "correct_index": 3,
    "explanation": "Soil is the Realists Stabilizer.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Soil"
  },
  {
    "id": "q0050",
    "prompt": "Which Creator is the Optimists Integrator?",
    "options": [
      "Lava",
      "Lake",
      "Whirlwind",
      "Sun"
    ],
    "correct_index": 3,
    "explanation": "Sun is the Optimists Integrator.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Sun"
  },
  {
    "id": "q0051",
    "prompt": "Which Creator is the Humanists Integrator?",
    "options": [
      "Soil",
      "Sky",
      "Lava",
      "Tree"
    ],
    "correct_index": 3,
    "explanation": "Tree is the Humanists Integrator.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Tree"
  },
  {
    "id": "q0052",
    "prompt": "Which Creator is the Catalysts Integrator?",
    "options": [
      "Mountain",
      "Whirlwind",
      "Sun",
      "Lightning"
    ],
    "correct_index": 1,
    "explanation": "Whirlwind is the Catalysts Integrator.",
    "style": "reverse_family_role",
    "category": "reverse",
    "creator": "Whirlwind"
  },
  {
    "id": "q0053",
    "prompt": "Which Creator has this Natural State?\n\n\"___'s gift is warmth that travels.\"",
    "options": [
      "Snow",
      "Fire",
      "Sun",
      "Lightning"
    ],
    "correct_index": 1,
    "explanation": "That's the signature of the Fire Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Fire"
  },
  {
    "id": "q0054",
    "prompt": "Which Creator has this Natural State?\n\n\"___'s power is the still surface that shows things back exactly as they are.\"",
    "options": [
      "River",
      "Sun",
      "Snow",
      "Lake"
    ],
    "correct_index": 3,
    "explanation": "That's the signature of the Lake Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Lake"
  },
  {
    "id": "q0055",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is the only Creator that makes new ground.\"",
    "options": [
      "Lava",
      "Ocean",
      "Whirlwind",
      "Sky"
    ],
    "correct_index": 0,
    "explanation": "That's the signature of the Lava Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Lava"
  },
  {
    "id": "q0056",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is the flash of recognition — the moment a complicated thing suddenly becomes simple.\"",
    "options": [
      "Lava",
      "Mountain",
      "Lightning",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "That's the signature of the Lightning Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Lightning"
  },
  {
    "id": "q0057",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is what doesn't move.\"",
    "options": [
      "Mountain",
      "Soil",
      "Snow",
      "Tree"
    ],
    "correct_index": 0,
    "explanation": "That's the signature of the Mountain Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Mountain"
  },
  {
    "id": "q0058",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is the deepest version of every Water type.\"",
    "options": [
      "Lava",
      "Ocean",
      "Tree",
      "Mountain"
    ],
    "correct_index": 1,
    "explanation": "That's the signature of the Ocean Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Ocean"
  },
  {
    "id": "q0059",
    "prompt": "Which Creator has this Natural State?\n\n\"___'s power isn't strength — it's persistence.\"",
    "options": [
      "River",
      "Mountain",
      "Ocean",
      "Sun"
    ],
    "correct_index": 0,
    "explanation": "That's the signature of the River Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "River"
  },
  {
    "id": "q0060",
    "prompt": "Which Creator has this Natural State?\n\n\"___'s natural power is the room itself.\"",
    "options": [
      "Snow",
      "Whirlwind",
      "River",
      "Sky"
    ],
    "correct_index": 3,
    "explanation": "That's the signature of the Sky Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Sky"
  },
  {
    "id": "q0061",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is the quietest force in the system.\"",
    "options": [
      "Sky",
      "Lake",
      "Mountain",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "That's the signature of the Snow Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Snow"
  },
  {
    "id": "q0062",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is what makes everything else possible.\"",
    "options": [
      "Tree",
      "Soil",
      "Lake",
      "Mountain"
    ],
    "correct_index": 1,
    "explanation": "That's the signature of the Soil Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Soil"
  },
  {
    "id": "q0063",
    "prompt": "Which Creator has this Natural State?\n\n\"___ is the source.\"",
    "options": [
      "Sun",
      "Sky",
      "Lake",
      "Mountain"
    ],
    "correct_index": 0,
    "explanation": "That's the signature of the Sun Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Sun"
  },
  {
    "id": "q0064",
    "prompt": "Which Creator has this Natural State?\n\n\"___'s gift is time made visible.\"",
    "options": [
      "Lake",
      "Tree",
      "Sun",
      "Ocean"
    ],
    "correct_index": 1,
    "explanation": "That's the signature of the Tree Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Tree"
  },
  {
    "id": "q0065",
    "prompt": "Which Creator has this Natural State?\n\n\"___ doesn't move in straight lines — it spirals.\"",
    "options": [
      "Sun",
      "Lava",
      "Whirlwind",
      "Lake"
    ],
    "correct_index": 2,
    "explanation": "That's the signature of the Whirlwind Creator.",
    "style": "signature_whoami",
    "category": "signature",
    "creator": "Whirlwind"
  },
  {
    "id": "q0066",
    "prompt": "Which Creator's Disaster State is this?\n\n\"A ___ out of balance becomes a wildfire — consuming oxygen, consuming attention, consuming the very thing it was meant to nourish.\"",
    "options": [
      "Lightning",
      "Sky",
      "Ocean",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "That's how Fire looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Fire"
  },
  {
    "id": "q0067",
    "prompt": "Which Creator's Disaster State is this?\n\n\"Stillness that loses its current becomes stagnation.\"",
    "options": [
      "Ocean",
      "River",
      "Tree",
      "Lake"
    ],
    "correct_index": 3,
    "explanation": "That's how Lake looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Lake"
  },
  {
    "id": "q0068",
    "prompt": "Which Creator's Disaster State is this?\n\n\"When ___ runs unchecked, the eruption stops being generative and starts being scorched earth.\"",
    "options": [
      "Tree",
      "River",
      "Soil",
      "Lava"
    ],
    "correct_index": 3,
    "explanation": "That's how Lava looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Lava"
  },
  {
    "id": "q0069",
    "prompt": "Which Creator's Disaster State is this?\n\n\"When ___ loses its ground, the strikes turn into a storm — too many flashes, too fast, none of them connecting to action.\"",
    "options": [
      "Sun",
      "Whirlwind",
      "Lightning",
      "Ocean"
    ],
    "correct_index": 2,
    "explanation": "That's how Lightning looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Lightning"
  },
  {
    "id": "q0070",
    "prompt": "Which Creator's Disaster State is this?\n\n\"A ___ that holds for too long, or holds the wrong thing, quietly builds pressure underneath itself.\"",
    "options": [
      "Mountain",
      "Lake",
      "Soil",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "That's how Mountain looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Mountain"
  },
  {
    "id": "q0071",
    "prompt": "Which Creator's Disaster State is this?\n\n\"An ___ disturbed at depth doesn't react with ripples — it reacts with a tsunami.\"",
    "options": [
      "Lava",
      "Sun",
      "Ocean",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "That's how Ocean looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Ocean"
  },
  {
    "id": "q0072",
    "prompt": "Which Creator's Disaster State is this?\n\n\"A ___ without banks becomes a flood.\"",
    "options": [
      "Snow",
      "Lava",
      "River",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "That's how River looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "River"
  },
  {
    "id": "q0073",
    "prompt": "Which Creator's Disaster State is this?\n\n\"___ in disorder becomes turbulence — endless reframing, endless zoom-outs, endless \"but what if we considered this from another angle.\" The same expansive gift, ungrounded, becomes the reason nothing ever lands.\"",
    "options": [
      "Sun",
      "River",
      "Tree",
      "Sky"
    ],
    "correct_index": 3,
    "explanation": "That's how Sky looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Sky"
  },
  {
    "id": "q0074",
    "prompt": "Which Creator's Disaster State is this?\n\n\"___ that loses its lightness becomes an avalanche — all that quiet, patient covering, suddenly released as one downhill rush that buries everything in its path.\"",
    "options": [
      "River",
      "Lake",
      "Ocean",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "That's how Snow looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Snow"
  },
  {
    "id": "q0075",
    "prompt": "Which Creator's Disaster State is this?\n\n\"___ left unprotected, overworked, or undervalued erodes.\"",
    "options": [
      "Soil",
      "Sky",
      "Tree",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "That's how Soil looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Soil"
  },
  {
    "id": "q0076",
    "prompt": "Which Creator's Disaster State is this?\n\n\"A ___ overheating becomes a solar flare — too much output, too little rhythm, scorching the very ecosystem it was sustaining.\"",
    "options": [
      "Soil",
      "Mountain",
      "Sun",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "That's how Sun looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Sun"
  },
  {
    "id": "q0077",
    "prompt": "Which Creator's Disaster State is this?\n\n\"A ___ forced out of season — moved too often, asked to grow too fast, denied root time — becomes an uprooting waiting to happen.\"",
    "options": [
      "Lightning",
      "Whirlwind",
      "Tree",
      "Sun"
    ],
    "correct_index": 2,
    "explanation": "That's how Tree looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Tree"
  },
  {
    "id": "q0078",
    "prompt": "Which Creator's Disaster State is this?\n\n\"When ___ loses its still centre, the spiral becomes a tornado — change for change's sake, with no anchor and nowhere to land.\"",
    "options": [
      "Tree",
      "Sky",
      "Whirlwind",
      "Lava"
    ],
    "correct_index": 2,
    "explanation": "That's how Whirlwind looks in shadow.",
    "style": "shadow_whoami",
    "category": "shadow",
    "creator": "Whirlwind"
  },
  {
    "id": "q0079",
    "prompt": "Which Creator shows up at the table like this?\n\n\"A Catalyst, but a Stabilizer — which means ___ is the rare combination that brings the energy and keeps it lit.\"",
    "options": [
      "Sun",
      "Soil",
      "Fire",
      "Whirlwind"
    ],
    "correct_index": 2,
    "explanation": "That's the Fire contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Fire"
  },
  {
    "id": "q0080",
    "prompt": "Which Creator shows up at the table like this?\n\n\"A Humanist Director who leads by holding space, not by pushing.\"",
    "options": [
      "Mountain",
      "Whirlwind",
      "Lake",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "That's the Lake contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Lake"
  },
  {
    "id": "q0081",
    "prompt": "Which Creator shows up at the table like this?\n\n\"As a Catalyst Director, ___ is the one who says the unsayable in the meeting.\"",
    "options": [
      "Whirlwind",
      "Lake",
      "Lava",
      "Tree"
    ],
    "correct_index": 2,
    "explanation": "That's the Lava contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Lava"
  },
  {
    "id": "q0082",
    "prompt": "Which Creator shows up at the table like this?\n\n\"An Optimist Stabilizer who works by strike — long stretches of listening, then one sentence that reframes the entire conversation.\"",
    "options": [
      "Soil",
      "Ocean",
      "Lightning",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "That's the Lightning contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Lightning"
  },
  {
    "id": "q0083",
    "prompt": "Which Creator shows up at the table like this?\n\n\"A Realist Director who builds structures that outlast the conversation that created them.\"",
    "options": [
      "Snow",
      "Mountain",
      "Fire",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "That's the Mountain contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Mountain"
  },
  {
    "id": "q0084",
    "prompt": "Which Creator shows up at the table like this?\n\n\"A Humanist Stabilizer whose contribution is often a single, slow sentence that goes deeper than the last twenty minutes of conversation combined.\"",
    "options": [
      "Fire",
      "Whirlwind",
      "Ocean",
      "Lake"
    ],
    "correct_index": 2,
    "explanation": "That's the Ocean contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Ocean"
  },
  {
    "id": "q0085",
    "prompt": "Which Creator shows up at the table like this?\n\n\"A Realist Integrator who keeps the work moving.\"",
    "options": [
      "River",
      "Whirlwind",
      "Lava",
      "Lake"
    ],
    "correct_index": 0,
    "explanation": "That's the River contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "River"
  },
  {
    "id": "q0086",
    "prompt": "Which Creator shows up at the table like this?\n\n\"As The Visionary, ___'s role isn't to do the work — it's to keep the horizon visible while the work is being done.\"",
    "options": [
      "Lava",
      "Sky",
      "Fire",
      "Snow"
    ],
    "correct_index": 1,
    "explanation": "That's the Sky contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Sky"
  },
  {
    "id": "q0087",
    "prompt": "Which Creator shows up at the table like this?\n\n\"An Optimist Director who leads by lowering the temperature.\"",
    "options": [
      "Snow",
      "Whirlwind",
      "Sun",
      "Soil"
    ],
    "correct_index": 0,
    "explanation": "That's the Snow contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Snow"
  },
  {
    "id": "q0088",
    "prompt": "Which Creator shows up at the table like this?\n\n\"A Realist Stabilizer who feeds the team without ever needing to be at the front of the room.\"",
    "options": [
      "Soil",
      "Tree",
      "River",
      "Lightning"
    ],
    "correct_index": 0,
    "explanation": "That's the Soil contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Soil"
  },
  {
    "id": "q0089",
    "prompt": "Which Creator shows up at the table like this?\n\n\"An Optimist Integrator means ___ pulls together what's already there and sees what it could become.\"",
    "options": [
      "Soil",
      "Whirlwind",
      "Sun",
      "Mountain"
    ],
    "correct_index": 2,
    "explanation": "That's the Sun contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Sun"
  },
  {
    "id": "q0090",
    "prompt": "Which Creator shows up at the table like this?\n\n\"As a Humanist Integrator, ___ is the type that weaves people, projects, and seasons into something that compounds.\"",
    "options": [
      "Lava",
      "Mountain",
      "Tree",
      "Soil"
    ],
    "correct_index": 2,
    "explanation": "That's the Tree contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Tree"
  },
  {
    "id": "q0091",
    "prompt": "Which Creator shows up at the table like this?\n\n\"As an Integrator, ___ is the one who picks things up from every corner of the room and weaves them into something nobody else saw was there.\"",
    "options": [
      "Mountain",
      "Ocean",
      "Whirlwind",
      "Soil"
    ],
    "correct_index": 2,
    "explanation": "That's the Whirlwind contribution at the table.",
    "style": "at_table_whoami",
    "category": "at_table",
    "creator": "Whirlwind"
  },
  {
    "id": "q0092",
    "prompt": "You might be which Creator if...\n\n\"People describe being around you as \"energising,\" you've ever realised you've been quietly carrying a group's enthusiasm on your back, and you suspect that what most projects are missing isn't a better plan — it's heat.\"",
    "options": [
      "Fire",
      "Ocean",
      "River",
      "Soil"
    ],
    "correct_index": 0,
    "explanation": "That's a classic Fire tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Fire"
  },
  {
    "id": "q0093",
    "prompt": "You might be which Creator if...\n\n\"Friends seek you out specifically because you don't react — you just receive, and somehow in the receiving, they figure out what they actually think.\"",
    "options": [
      "Lake",
      "Tree",
      "Sun",
      "Whirlwind"
    ],
    "correct_index": 0,
    "explanation": "That's a classic Lake tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Lake"
  },
  {
    "id": "q0094",
    "prompt": "You might be which Creator if...\n\n\"You have a low tolerance for \"this is just how things are here,\" confrontation feels easier to you than going-along-to-get-along, and you've noticed that you tend to be the person who finally just names the thing in a room full of people pretending not to see it.\"",
    "options": [
      "Lava",
      "Lake",
      "Lightning",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "That's a classic Lava tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Lava"
  },
  {
    "id": "q0095",
    "prompt": "You might be which Creator if...\n\n\"You arrive at conclusions before you can explain how, you find slow linear meetings genuinely painful, and you've noticed that your best ideas tend to land in the shower, on a walk, or right as you were about to fall asleep.\"",
    "options": [
      "Mountain",
      "Tree",
      "Snow",
      "Lightning"
    ],
    "correct_index": 3,
    "explanation": "That's a classic Lightning tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Lightning"
  },
  {
    "id": "q0096",
    "prompt": "You might be which Creator if...\n\n\"People describe you with words like \"solid,\" \"reliable,\" \"rock,\" and you suspect they mean it as both a compliment and a slight underestimate.\"",
    "options": [
      "Tree",
      "River",
      "Lava",
      "Mountain"
    ],
    "correct_index": 3,
    "explanation": "That's a classic Mountain tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Mountain"
  },
  {
    "id": "q0097",
    "prompt": "You might be which Creator if...\n\n\"People tell you things they haven't told anyone else, you've been carrying more than you've ever discussed, and you've noticed that \"still waters run deep\" was meant to be a poetic phrase — but in your case is also just accurate.\"",
    "options": [
      "Tree",
      "Lava",
      "Ocean",
      "Soil"
    ],
    "correct_index": 2,
    "explanation": "That's a classic Ocean tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Ocean"
  },
  {
    "id": "q0098",
    "prompt": "You might be which Creator if...\n\n\"You genuinely cannot sit still for very long, your relationship with creativity is \"the work just kind of pours out of me when I let it,\" and you've been told both \"you're so productive\" and \"you really need to slow down\" by people who couldn't see they were describing the same trait.\"",
    "options": [
      "Sky",
      "Mountain",
      "River",
      "Lightning"
    ],
    "correct_index": 2,
    "explanation": "That's a classic River tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "River"
  },
  {
    "id": "q0099",
    "prompt": "You might be which Creator if...\n\n\"You struggle to stay interested in the next step but light up at the ten-year horizon, you instinctively connect things other people experience as unrelated, and you've noticed that you do your best thinking with your gaze pointed at something open — water, a window, a wide field.\"",
    "options": [
      "Sky",
      "Lava",
      "Whirlwind",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "That's a classic Sky tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Sky"
  },
  {
    "id": "q0100",
    "prompt": "You might be which Creator if...\n\n\"You are unreasonably particular about details other people can't even see, your presence tends to slow conversations down in a good way, and you've been told you're \"still waters\" by someone who clearly suspected there was a current underneath.\"",
    "options": [
      "Ocean",
      "Soil",
      "Sky",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "That's a classic Snow tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Snow"
  },
  {
    "id": "q0101",
    "prompt": "You might be which Creator if...\n\n\"You're the one people return to between adventures, \"I don't know how this would work without you\" has been said to you more than once, and you've noticed that your generosity is the one thing that occasionally needs you to be selfish about it.\"",
    "options": [
      "Lake",
      "Sky",
      "Soil",
      "Fire"
    ],
    "correct_index": 2,
    "explanation": "That's a classic Soil tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Soil"
  },
  {
    "id": "q0102",
    "prompt": "You might be which Creator if...\n\n\"People come away from conversations with you feeling like they have more energy than they came in with, you naturally describe futures that haven't happened yet as if they already exist, and you suspect that steady might be one of your most underestimated superpowers.\"",
    "options": [
      "Sun",
      "Fire",
      "Soil",
      "Whirlwind"
    ],
    "correct_index": 0,
    "explanation": "That's a classic Sun tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Sun"
  },
  {
    "id": "q0103",
    "prompt": "You might be which Creator if...\n\n\"Your best work is invisible to people who only know you for a year, you've been told you're \"patient\" in a way that almost sounded like an accusation, and you have a quiet, slightly stubborn relationship with the places, projects, and people you've decided to grow next to.\"",
    "options": [
      "Fire",
      "Whirlwind",
      "Lightning",
      "Tree"
    ],
    "correct_index": 3,
    "explanation": "That's a classic Tree tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Tree"
  },
  {
    "id": "q0104",
    "prompt": "You might be which Creator if...\n\n\"You can't remember a six-month period of your life where everything stayed the same, you accidentally restructure groups just by being in them, and you find slow incremental change physically uncomfortable.\"",
    "options": [
      "Lake",
      "Tree",
      "Whirlwind",
      "Soil"
    ],
    "correct_index": 2,
    "explanation": "That's a classic Whirlwind tell.",
    "style": "ymbi_whoami",
    "category": "ymbi",
    "creator": "Whirlwind"
  },
  {
    "id": "q0105",
    "prompt": "Which of these Creators shares the same Family as Fire?",
    "options": [
      "River",
      "Lava",
      "Sun",
      "Lake"
    ],
    "correct_index": 1,
    "explanation": "Both Fire and Lava are Catalysts.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Fire"
  },
  {
    "id": "q0106",
    "prompt": "Which of these Creators shares the same Family as Lake?",
    "options": [
      "Ocean",
      "River",
      "Lightning",
      "Fire"
    ],
    "correct_index": 0,
    "explanation": "Both Lake and Ocean are Humanists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Lake"
  },
  {
    "id": "q0107",
    "prompt": "Which of these Creators shares the same Family as Lava?",
    "options": [
      "Soil",
      "Sun",
      "Fire",
      "Lake"
    ],
    "correct_index": 2,
    "explanation": "Both Lava and Fire are Catalysts.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Lava"
  },
  {
    "id": "q0108",
    "prompt": "Which of these Creators shares the same Family as Lightning?",
    "options": [
      "Snow",
      "Fire",
      "Sky",
      "Soil"
    ],
    "correct_index": 0,
    "explanation": "Both Lightning and Snow are Optimists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Lightning"
  },
  {
    "id": "q0109",
    "prompt": "Which of these Creators shares the same Family as Mountain?",
    "options": [
      "Lava",
      "Tree",
      "Ocean",
      "Soil"
    ],
    "correct_index": 3,
    "explanation": "Both Mountain and Soil are Realists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Mountain"
  },
  {
    "id": "q0110",
    "prompt": "Which of these Creators shares the same Family as Ocean?",
    "options": [
      "Mountain",
      "Sky",
      "Lightning",
      "Lake"
    ],
    "correct_index": 3,
    "explanation": "Both Ocean and Lake are Humanists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Ocean"
  },
  {
    "id": "q0111",
    "prompt": "Which of these Creators shares the same Family as River?",
    "options": [
      "Fire",
      "Soil",
      "Sun",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "Both River and Soil are Realists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "River"
  },
  {
    "id": "q0112",
    "prompt": "Which of these Creators shares the same Family as Snow?",
    "options": [
      "Ocean",
      "Sky",
      "Sun",
      "Fire"
    ],
    "correct_index": 2,
    "explanation": "Both Snow and Sun are Optimists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Snow"
  },
  {
    "id": "q0113",
    "prompt": "Which of these Creators shares the same Family as Soil?",
    "options": [
      "Lava",
      "Lake",
      "Sun",
      "Mountain"
    ],
    "correct_index": 3,
    "explanation": "Both Soil and Mountain are Realists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Soil"
  },
  {
    "id": "q0114",
    "prompt": "Which of these Creators shares the same Family as Sun?",
    "options": [
      "Ocean",
      "Lava",
      "River",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "Both Sun and Snow are Optimists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Sun"
  },
  {
    "id": "q0115",
    "prompt": "Which of these Creators shares the same Family as Tree?",
    "options": [
      "Lightning",
      "Ocean",
      "Soil",
      "Snow"
    ],
    "correct_index": 1,
    "explanation": "Both Tree and Ocean are Humanists.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Tree"
  },
  {
    "id": "q0116",
    "prompt": "Which of these Creators shares the same Family as Whirlwind?",
    "options": [
      "Fire",
      "Sun",
      "Ocean",
      "River"
    ],
    "correct_index": 0,
    "explanation": "Both Whirlwind and Fire are Catalysts.",
    "style": "compare_family",
    "category": "compare",
    "creator": "Whirlwind"
  },
  {
    "id": "q0117",
    "prompt": "Which Creator shares Fire's element (Fire)?",
    "options": [
      "River",
      "Lava",
      "Ocean",
      "Lightning"
    ],
    "correct_index": 1,
    "explanation": "Fire and Lava are both Fire types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Fire"
  },
  {
    "id": "q0118",
    "prompt": "Which Creator shares Lake's element (Water)?",
    "options": [
      "Snow",
      "Lava",
      "Soil",
      "River"
    ],
    "correct_index": 3,
    "explanation": "Lake and River are both Water types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Lake"
  },
  {
    "id": "q0119",
    "prompt": "Which Creator shares Lava's element (Fire)?",
    "options": [
      "Sun",
      "Tree",
      "Lightning",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "Lava and Sun are both Fire types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Lava"
  },
  {
    "id": "q0120",
    "prompt": "Which Creator shares Lightning's element (Air)?",
    "options": [
      "Sun",
      "Tree",
      "Soil",
      "Whirlwind"
    ],
    "correct_index": 3,
    "explanation": "Lightning and Whirlwind are both Air types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Lightning"
  },
  {
    "id": "q0121",
    "prompt": "Which Creator shares Mountain's element (Earth)?",
    "options": [
      "Soil",
      "Lightning",
      "Whirlwind",
      "Fire"
    ],
    "correct_index": 0,
    "explanation": "Mountain and Soil are both Earth types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Mountain"
  },
  {
    "id": "q0122",
    "prompt": "Which Creator shares Ocean's element (Water)?",
    "options": [
      "Mountain",
      "Sun",
      "Sky",
      "River"
    ],
    "correct_index": 3,
    "explanation": "Ocean and River are both Water types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Ocean"
  },
  {
    "id": "q0123",
    "prompt": "Which Creator shares River's element (Water)?",
    "options": [
      "Lake",
      "Mountain",
      "Tree",
      "Sky"
    ],
    "correct_index": 0,
    "explanation": "River and Lake are both Water types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "River"
  },
  {
    "id": "q0124",
    "prompt": "Which Creator shares Sky's element (Air)?",
    "options": [
      "Snow",
      "River",
      "Soil",
      "Sun"
    ],
    "correct_index": 0,
    "explanation": "Sky and Snow are both Air types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Sky"
  },
  {
    "id": "q0125",
    "prompt": "Which Creator shares Snow's element (Air)?",
    "options": [
      "River",
      "Sky",
      "Fire",
      "Soil"
    ],
    "correct_index": 1,
    "explanation": "Snow and Sky are both Air types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Snow"
  },
  {
    "id": "q0126",
    "prompt": "Which Creator shares Soil's element (Earth)?",
    "options": [
      "Mountain",
      "Fire",
      "Lake",
      "Lightning"
    ],
    "correct_index": 0,
    "explanation": "Soil and Mountain are both Earth types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Soil"
  },
  {
    "id": "q0127",
    "prompt": "Which Creator shares Sun's element (Fire)?",
    "options": [
      "Fire",
      "Whirlwind",
      "Tree",
      "Soil"
    ],
    "correct_index": 0,
    "explanation": "Sun and Fire are both Fire types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Sun"
  },
  {
    "id": "q0128",
    "prompt": "Which Creator shares Tree's element (Earth)?",
    "options": [
      "Lava",
      "Whirlwind",
      "Soil",
      "Fire"
    ],
    "correct_index": 2,
    "explanation": "Tree and Soil are both Earth types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Tree"
  },
  {
    "id": "q0129",
    "prompt": "Which Creator shares Whirlwind's element (Air)?",
    "options": [
      "Mountain",
      "Lava",
      "Fire",
      "Lightning"
    ],
    "correct_index": 3,
    "explanation": "Whirlwind and Lightning are both Air types.",
    "style": "compare_element",
    "category": "compare",
    "creator": "Whirlwind"
  },
  {
    "id": "q0130",
    "prompt": "Which of these Creators is NOT a Catalysts Family member?",
    "options": [
      "Snow",
      "Whirlwind",
      "Fire",
      "Lava"
    ],
    "correct_index": 0,
    "explanation": "Snow is a Optimists, not a Catalysts.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0131",
    "prompt": "Which of these Creators is NOT a Catalysts Family member?",
    "options": [
      "Whirlwind",
      "Lake",
      "Lava",
      "Fire"
    ],
    "correct_index": 1,
    "explanation": "Lake is a Humanists, not a Catalysts.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0132",
    "prompt": "Which of these Creators is NOT a Catalysts Family member?",
    "options": [
      "Whirlwind",
      "Lava",
      "Snow",
      "Fire"
    ],
    "correct_index": 2,
    "explanation": "Snow is a Optimists, not a Catalysts.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0133",
    "prompt": "Which of these Creators is NOT a Humanists Family member?",
    "options": [
      "Ocean",
      "Tree",
      "Soil",
      "Lake"
    ],
    "correct_index": 2,
    "explanation": "Soil is a Realists, not a Humanists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0134",
    "prompt": "Which of these Creators is NOT a Humanists Family member?",
    "options": [
      "Lake",
      "Tree",
      "Ocean",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "Snow is a Optimists, not a Humanists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0135",
    "prompt": "Which of these Creators is NOT a Humanists Family member?",
    "options": [
      "Ocean",
      "Lake",
      "Tree",
      "Mountain"
    ],
    "correct_index": 3,
    "explanation": "Mountain is a Realists, not a Humanists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0136",
    "prompt": "Which of these Creators is NOT a Optimists Family member?",
    "options": [
      "Snow",
      "Fire",
      "Lightning",
      "Sun"
    ],
    "correct_index": 1,
    "explanation": "Fire is a Catalysts, not a Optimists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0137",
    "prompt": "Which of these Creators is NOT a Optimists Family member?",
    "options": [
      "Tree",
      "Lightning",
      "Snow",
      "Sun"
    ],
    "correct_index": 0,
    "explanation": "Tree is a Humanists, not a Optimists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0138",
    "prompt": "Which of these Creators is NOT a Optimists Family member?",
    "options": [
      "Sun",
      "Snow",
      "Lightning",
      "Soil"
    ],
    "correct_index": 3,
    "explanation": "Soil is a Realists, not a Optimists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0139",
    "prompt": "Which of these Creators is NOT a Realists Family member?",
    "options": [
      "Lake",
      "River",
      "Soil",
      "Mountain"
    ],
    "correct_index": 0,
    "explanation": "Lake is a Humanists, not a Realists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0140",
    "prompt": "Which of these Creators is NOT a Realists Family member?",
    "options": [
      "Mountain",
      "Lake",
      "Soil",
      "River"
    ],
    "correct_index": 1,
    "explanation": "Lake is a Humanists, not a Realists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0141",
    "prompt": "Which of these Creators is NOT a Realists Family member?",
    "options": [
      "Ocean",
      "River",
      "Soil",
      "Mountain"
    ],
    "correct_index": 0,
    "explanation": "Ocean is a Humanists, not a Realists.",
    "style": "not_family",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0142",
    "prompt": "Which of these Creators is NOT a Air type?",
    "options": [
      "Sky",
      "Tree",
      "Snow",
      "Whirlwind"
    ],
    "correct_index": 1,
    "explanation": "Tree is Earth, not Air.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0143",
    "prompt": "Which of these Creators is NOT a Air type?",
    "options": [
      "Snow",
      "Whirlwind",
      "Sun",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "Sun is Fire, not Air.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0144",
    "prompt": "Which of these Creators is NOT a Air type?",
    "options": [
      "River",
      "Whirlwind",
      "Sky",
      "Snow"
    ],
    "correct_index": 0,
    "explanation": "River is Water, not Air.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0145",
    "prompt": "Which of these Creators is NOT a Earth type?",
    "options": [
      "Mountain",
      "Sky",
      "Tree",
      "Soil"
    ],
    "correct_index": 1,
    "explanation": "Sky is Air, not Earth.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0146",
    "prompt": "Which of these Creators is NOT a Earth type?",
    "options": [
      "Tree",
      "Whirlwind",
      "Soil",
      "Mountain"
    ],
    "correct_index": 1,
    "explanation": "Whirlwind is Air, not Earth.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0147",
    "prompt": "Which of these Creators is NOT a Earth type?",
    "options": [
      "Ocean",
      "Soil",
      "Tree",
      "Mountain"
    ],
    "correct_index": 0,
    "explanation": "Ocean is Water, not Earth.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0148",
    "prompt": "Which of these Creators is NOT a Fire type?",
    "options": [
      "Fire",
      "Lava",
      "Sun",
      "Lightning"
    ],
    "correct_index": 3,
    "explanation": "Lightning is Air, not Fire.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0149",
    "prompt": "Which of these Creators is NOT a Fire type?",
    "options": [
      "Sun",
      "Soil",
      "Fire",
      "Lava"
    ],
    "correct_index": 1,
    "explanation": "Soil is Earth, not Fire.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0150",
    "prompt": "Which of these Creators is NOT a Fire type?",
    "options": [
      "Lava",
      "Ocean",
      "Fire",
      "Sun"
    ],
    "correct_index": 1,
    "explanation": "Ocean is Water, not Fire.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0151",
    "prompt": "Which of these Creators is NOT a Water type?",
    "options": [
      "Lake",
      "Snow",
      "Ocean",
      "River"
    ],
    "correct_index": 1,
    "explanation": "Snow is Air, not Water.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0152",
    "prompt": "Which of these Creators is NOT a Water type?",
    "options": [
      "Ocean",
      "Snow",
      "Lake",
      "River"
    ],
    "correct_index": 1,
    "explanation": "Snow is Air, not Water.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0153",
    "prompt": "Which of these Creators is NOT a Water type?",
    "options": [
      "Lake",
      "Ocean",
      "River",
      "Mountain"
    ],
    "correct_index": 3,
    "explanation": "Mountain is Earth, not Water.",
    "style": "not_element",
    "category": "exclusion",
    "creator": null
  },
  {
    "id": "q0154",
    "prompt": "The Alpaca card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Lightning",
      "Snow",
      "Whirlwind"
    ],
    "correct_index": 2,
    "explanation": "Alpaca = Snow + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0155",
    "prompt": "The Anteater card is which Creator type? (pick one)",
    "options": [
      "Lightning",
      "Mountain",
      "Soil",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "Anteater = Soil + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0156",
    "prompt": "The Bear card is which Creator type? (pick one)",
    "options": [
      "Lake",
      "Lightning",
      "Ocean",
      "Lava"
    ],
    "correct_index": 3,
    "explanation": "Bear = Lava + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0157",
    "prompt": "The Beaver card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Lake",
      "Sky",
      "Mountain"
    ],
    "correct_index": 1,
    "explanation": "Beaver = Lake + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0158",
    "prompt": "The Bee card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Tree",
      "Mountain",
      "Lava"
    ],
    "correct_index": 3,
    "explanation": "Bee = Lava + Snow.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0159",
    "prompt": "The Bigfoot card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Tree",
      "Mountain",
      "Whirlwind"
    ],
    "correct_index": 2,
    "explanation": "Bigfoot = Mountain + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0160",
    "prompt": "The Bison card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Lake",
      "River",
      "Mountain"
    ],
    "correct_index": 3,
    "explanation": "Bison = Mountain + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0161",
    "prompt": "The Bunyip card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Lightning",
      "Lake",
      "River"
    ],
    "correct_index": 2,
    "explanation": "Bunyip = Lake + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0162",
    "prompt": "The Camel card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Mountain",
      "Fire",
      "Lightning"
    ],
    "correct_index": 2,
    "explanation": "Camel = Fire + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0163",
    "prompt": "The Cassowary card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Lava",
      "River",
      "Soil"
    ],
    "correct_index": 1,
    "explanation": "Cassowary = Lava + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0164",
    "prompt": "The Catfish card is which Creator type? (pick one)",
    "options": [
      "Lake",
      "Soil",
      "Lightning",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "Catfish = Lightning + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0165",
    "prompt": "The Cheetah card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Mountain",
      "Ocean",
      "River"
    ],
    "correct_index": 0,
    "explanation": "Cheetah = Fire + Lightning.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0166",
    "prompt": "The Crab card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Snow",
      "Lava",
      "Lake"
    ],
    "correct_index": 3,
    "explanation": "Crab = Lake + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0167",
    "prompt": "The Crane card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Lightning",
      "River",
      "Snow"
    ],
    "correct_index": 1,
    "explanation": "Crane = Lightning + Lake.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0168",
    "prompt": "The Crocodile card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Whirlwind",
      "River",
      "Ocean"
    ],
    "correct_index": 3,
    "explanation": "Crocodile = Ocean + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0169",
    "prompt": "The Deer card is which Creator type? (pick one)",
    "options": [
      "Sky",
      "Soil",
      "Fire",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "Deer = Snow + Lightning.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0170",
    "prompt": "The Dolphin card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Tree",
      "Sky",
      "Whirlwind"
    ],
    "correct_index": 3,
    "explanation": "Dolphin = Whirlwind + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0171",
    "prompt": "The Dragon card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Lake",
      "Fire",
      "Lava"
    ],
    "correct_index": 2,
    "explanation": "Dragon = Fire + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0172",
    "prompt": "The Dragonfly card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "Lightning",
      "Whirlwind",
      "Mountain"
    ],
    "correct_index": 2,
    "explanation": "Dragonfly = Whirlwind + Lake.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0173",
    "prompt": "The Duck card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Whirlwind",
      "Mountain",
      "Lake"
    ],
    "correct_index": 0,
    "explanation": "Duck = Snow + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0174",
    "prompt": "The Echidna card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Sky",
      "Fire",
      "Lightning"
    ],
    "correct_index": 0,
    "explanation": "Echidna = Lava + Lake.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0175",
    "prompt": "The Eel card is which Creator type? (pick one)",
    "options": [
      "Sky",
      "Fire",
      "Tree",
      "Lava"
    ],
    "correct_index": 3,
    "explanation": "Eel = Lava + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0176",
    "prompt": "The Elephant card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Snow",
      "Lava",
      "Sun"
    ],
    "correct_index": 3,
    "explanation": "Elephant = Sun + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0177",
    "prompt": "The Elf card is which Creator type? (pick one)",
    "options": [
      "Sky",
      "Lake",
      "Whirlwind",
      "River"
    ],
    "correct_index": 0,
    "explanation": "Elf = Sky + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0178",
    "prompt": "The Fairy card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Lake",
      "Whirlwind",
      "Lava"
    ],
    "correct_index": 2,
    "explanation": "Fairy = Whirlwind + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0179",
    "prompt": "The Falcon card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Sun",
      "Lightning",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "Falcon = Lightning + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0180",
    "prompt": "The Firefly card is which Creator type? (pick one)",
    "options": [
      "River",
      "Whirlwind",
      "Fire",
      "Lake"
    ],
    "correct_index": 1,
    "explanation": "Firefly = Whirlwind + Lightning.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0181",
    "prompt": "The Flying Fox card is which Creator type? (pick one)",
    "options": [
      "Tree",
      "Lightning",
      "Lava",
      "Fire"
    ],
    "correct_index": 1,
    "explanation": "Flying Fox = Lightning + Sun.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0182",
    "prompt": "The Fox card is which Creator type? (pick one)",
    "options": [
      "Tree",
      "Lava",
      "Snow",
      "Whirlwind"
    ],
    "correct_index": 1,
    "explanation": "Fox = Lava + Fire.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0183",
    "prompt": "The Frog card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Sun",
      "Lake",
      "Lava"
    ],
    "correct_index": 2,
    "explanation": "Frog = Lake + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0184",
    "prompt": "The Giraffe card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "Sky",
      "Lightning",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "Giraffe = Lightning + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0185",
    "prompt": "The Goat card is which Creator type? (pick one)",
    "options": [
      "Tree",
      "Fire",
      "Snow",
      "Sun"
    ],
    "correct_index": 0,
    "explanation": "Goat = Tree + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0186",
    "prompt": "The Gorilla card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "River",
      "Fire",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "Gorilla = Fire + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0187",
    "prompt": "The Griffin card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Lava",
      "Soil",
      "Lake"
    ],
    "correct_index": 1,
    "explanation": "Griffin = Lava + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0188",
    "prompt": "The Hobbit card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Soil",
      "River",
      "Lava"
    ],
    "correct_index": 1,
    "explanation": "Hobbit = Soil + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0189",
    "prompt": "The Horse card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Whirlwind",
      "River",
      "Fire"
    ],
    "correct_index": 1,
    "explanation": "Horse = Whirlwind + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0190",
    "prompt": "The Iguana card is which Creator type? (pick one)",
    "options": [
      "Sky",
      "Lava",
      "Fire",
      "River"
    ],
    "correct_index": 1,
    "explanation": "Iguana = Lava + Sun.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0191",
    "prompt": "The Jellyfish card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Soil",
      "Whirlwind",
      "Lake"
    ],
    "correct_index": 3,
    "explanation": "Jellyfish = Lake + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0192",
    "prompt": "The Kangaroo card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Whirlwind",
      "Lightning",
      "River"
    ],
    "correct_index": 1,
    "explanation": "Kangaroo = Whirlwind + Sun.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0193",
    "prompt": "The Kingfisher card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Mountain",
      "Sun",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "Kingfisher = Sun + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0194",
    "prompt": "The Koala card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Sun",
      "Snow",
      "Soil"
    ],
    "correct_index": 1,
    "explanation": "Koala = Sun + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0195",
    "prompt": "The Lemur card is which Creator type? (pick one)",
    "options": [
      "Lake",
      "Sky",
      "Whirlwind",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "Lemur = Fire + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0196",
    "prompt": "The Leopard card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Snow",
      "Lava",
      "River"
    ],
    "correct_index": 1,
    "explanation": "Leopard = Snow + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0197",
    "prompt": "The Lion card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "Snow",
      "Soil",
      "Lightning"
    ],
    "correct_index": 0,
    "explanation": "Lion = Sun + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0198",
    "prompt": "The Lynx card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Mountain",
      "Whirlwind",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "Lynx = Mountain + Snow.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0199",
    "prompt": "The Merper card is which Creator type? (pick one)",
    "options": [
      "River",
      "Sun",
      "Mountain",
      "Ocean"
    ],
    "correct_index": 3,
    "explanation": "Merper = Ocean + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0200",
    "prompt": "The Mouse card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Sun",
      "Fire",
      "Lava"
    ],
    "correct_index": 2,
    "explanation": "Mouse = Fire + Snow.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0201",
    "prompt": "The Octopus card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Fire",
      "Lightning",
      "Sun"
    ],
    "correct_index": 0,
    "explanation": "Octopus = Lava + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0202",
    "prompt": "The Ostrich card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "Snow",
      "Mountain",
      "Whirlwind"
    ],
    "correct_index": 3,
    "explanation": "Ostrich = Whirlwind + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0203",
    "prompt": "The Otter card is which Creator type? (pick one)",
    "options": [
      "Lightning",
      "Sun",
      "Lava",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "Otter = Fire + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0204",
    "prompt": "The Panda card is which Creator type? (pick one)",
    "options": [
      "Tree",
      "River",
      "Fire",
      "Whirlwind"
    ],
    "correct_index": 2,
    "explanation": "Panda = Fire + Lake.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0205",
    "prompt": "The Peacock card is which Creator type? (pick one)",
    "options": [
      "Ocean",
      "Snow",
      "Fire",
      "Soil"
    ],
    "correct_index": 1,
    "explanation": "Peacock = Snow + Sun.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0206",
    "prompt": "The Penguin card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Sky",
      "Tree",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "Penguin = Snow + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0207",
    "prompt": "The Platypus card is which Creator type? (pick one)",
    "options": [
      "Lightning",
      "Mountain",
      "Fire",
      "Ocean"
    ],
    "correct_index": 0,
    "explanation": "Platypus = Lightning + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0208",
    "prompt": "The Rabbit card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Mountain",
      "Whirlwind",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "Rabbit = Whirlwind + Snow.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0209",
    "prompt": "The Rainbow Serpent card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Sun",
      "Ocean",
      "Lightning"
    ],
    "correct_index": 1,
    "explanation": "Rainbow Serpent = Sun + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0210",
    "prompt": "The Salamander card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Mountain",
      "Lake",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "Salamander = Mountain + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0211",
    "prompt": "The Seahorse card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Ocean",
      "Sun",
      "Sky"
    ],
    "correct_index": 1,
    "explanation": "Seahorse = Ocean + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0212",
    "prompt": "The Seal card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "Snow",
      "Whirlwind",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "Seal = Fire + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0213",
    "prompt": "The Seamonster card is which Creator type? (pick one)",
    "options": [
      "River",
      "Tree",
      "Lava",
      "Fire"
    ],
    "correct_index": 0,
    "explanation": "Seamonster = River + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0214",
    "prompt": "The Shark card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Sky",
      "Ocean",
      "Whirlwind"
    ],
    "correct_index": 3,
    "explanation": "Shark = Whirlwind + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0215",
    "prompt": "The Sloth card is which Creator type? (pick one)",
    "options": [
      "Sky",
      "Tree",
      "Ocean",
      "Whirlwind"
    ],
    "correct_index": 1,
    "explanation": "Sloth = Tree + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0216",
    "prompt": "The Snake card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Lightning",
      "Tree",
      "Sky"
    ],
    "correct_index": 2,
    "explanation": "Snake = Tree + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0217",
    "prompt": "The Spider card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Ocean",
      "Mountain",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "Spider = Snow + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0218",
    "prompt": "The Squirrel card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Snow",
      "Lava",
      "Fire"
    ],
    "correct_index": 3,
    "explanation": "Squirrel = Fire + Whirlwind.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0219",
    "prompt": "The Starfish card is which Creator type? (pick one)",
    "options": [
      "Lake",
      "Tree",
      "Fire",
      "Sun"
    ],
    "correct_index": 3,
    "explanation": "Starfish = Sun + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0220",
    "prompt": "The Stingray card is which Creator type? (pick one)",
    "options": [
      "Ocean",
      "Lake",
      "Lava",
      "Sky"
    ],
    "correct_index": 0,
    "explanation": "Stingray = Ocean + River.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0221",
    "prompt": "The Swan card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Lightning",
      "Mountain",
      "Ocean"
    ],
    "correct_index": 0,
    "explanation": "Swan = Snow + Lake.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0222",
    "prompt": "The Swordfish card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Sun",
      "Lightning",
      "Tree"
    ],
    "correct_index": 2,
    "explanation": "Swordfish = Lightning + Ocean.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0223",
    "prompt": "The Thunderbird card is which Creator type? (pick one)",
    "options": [
      "Whirlwind",
      "Lava",
      "Lightning",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "Thunderbird = Lightning + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0224",
    "prompt": "The Tiger card is which Creator type? (pick one)",
    "options": [
      "Fire",
      "Lava",
      "River",
      "Soil"
    ],
    "correct_index": 1,
    "explanation": "Tiger = Lava + Mountain.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0225",
    "prompt": "The Turtle card is which Creator type? (pick one)",
    "options": [
      "Tree",
      "Whirlwind",
      "Sun",
      "Mountain"
    ],
    "correct_index": 2,
    "explanation": "Turtle = Sun + Lake.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0226",
    "prompt": "The Unicorn card is which Creator type? (pick one)",
    "options": [
      "River",
      "Lava",
      "Soil",
      "Snow"
    ],
    "correct_index": 3,
    "explanation": "Unicorn = Snow + Sky.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0227",
    "prompt": "The Wasp card is which Creator type? (pick one)",
    "options": [
      "Soil",
      "Ocean",
      "Lava",
      "Fire"
    ],
    "correct_index": 2,
    "explanation": "Wasp = Lava + Lightning.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0228",
    "prompt": "The Whale card is which Creator type? (pick one)",
    "options": [
      "Snow",
      "Ocean",
      "Lake",
      "Lightning"
    ],
    "correct_index": 1,
    "explanation": "Whale = Ocean + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0229",
    "prompt": "The Wolf card is which Creator type? (pick one)",
    "options": [
      "Lava",
      "Whirlwind",
      "Sky",
      "Lightning"
    ],
    "correct_index": 0,
    "explanation": "Wolf = Lava + Snow.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0230",
    "prompt": "The Wombat card is which Creator type? (pick one)",
    "options": [
      "Tree",
      "Lake",
      "Sky",
      "Snow"
    ],
    "correct_index": 1,
    "explanation": "Wombat = Lake + Soil.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0231",
    "prompt": "The Woodpecker card is which Creator type? (pick one)",
    "options": [
      "Sun",
      "Ocean",
      "Whirlwind",
      "Snow"
    ],
    "correct_index": 2,
    "explanation": "Woodpecker = Whirlwind + Tree.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0232",
    "prompt": "The Zebra card is which Creator type? (pick one)",
    "options": [
      "Mountain",
      "Fire",
      "Sky",
      "Tree"
    ],
    "correct_index": 1,
    "explanation": "Zebra = Fire + Sun.",
    "style": "animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0233",
    "prompt": "Which of these animals is NOT a Snow type?",
    "options": [
      "Lynx",
      "Duck",
      "Alpaca",
      "Falcon"
    ],
    "correct_index": 3,
    "explanation": "Falcon is Lightning + Mountain — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0234",
    "prompt": "Which of these animals is NOT a Snow type?",
    "options": [
      "Spider",
      "Swan",
      "Eel",
      "Rabbit"
    ],
    "correct_index": 2,
    "explanation": "Eel is Lava + River — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0235",
    "prompt": "Which of these animals is NOT a Soil type?",
    "options": [
      "Platypus",
      "Seamonster",
      "Ostrich",
      "Camel"
    ],
    "correct_index": 1,
    "explanation": "Seamonster is River + Sky — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0236",
    "prompt": "Which of these animals is NOT a Soil type?",
    "options": [
      "Hobbit",
      "Platypus",
      "Wombat",
      "Echidna"
    ],
    "correct_index": 3,
    "explanation": "Echidna is Lava + Lake — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0237",
    "prompt": "Which of these animals is NOT a River type?",
    "options": [
      "Anteater",
      "Ostrich",
      "Stingray",
      "Catfish"
    ],
    "correct_index": 1,
    "explanation": "Ostrich is Whirlwind + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0238",
    "prompt": "Which of these animals is NOT a River type?",
    "options": [
      "Otter",
      "Anteater",
      "Shark",
      "Peacock"
    ],
    "correct_index": 3,
    "explanation": "Peacock is Snow + Sun — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0239",
    "prompt": "Which of these animals is NOT a Lava type?",
    "options": [
      "Sloth",
      "Bear",
      "Tiger",
      "Griffin"
    ],
    "correct_index": 0,
    "explanation": "Sloth is Tree + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0240",
    "prompt": "Which of these animals is NOT a Lava type?",
    "options": [
      "Echidna",
      "Wasp",
      "Bee",
      "Bigfoot"
    ],
    "correct_index": 3,
    "explanation": "Bigfoot is Mountain + Sky — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0241",
    "prompt": "Which of these animals is NOT a Lake type?",
    "options": [
      "Swan",
      "Beaver",
      "Bee",
      "Turtle"
    ],
    "correct_index": 2,
    "explanation": "Bee is Lava + Snow — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0242",
    "prompt": "Which of these animals is NOT a Lake type?",
    "options": [
      "Squirrel",
      "Beaver",
      "Echidna",
      "Crane"
    ],
    "correct_index": 0,
    "explanation": "Squirrel is Fire + Whirlwind — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0243",
    "prompt": "Which of these animals is NOT a Mountain type?",
    "options": [
      "Lynx",
      "Lion",
      "Tiger",
      "Camel"
    ],
    "correct_index": 3,
    "explanation": "Camel is Fire + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0244",
    "prompt": "Which of these animals is NOT a Mountain type?",
    "options": [
      "Tiger",
      "Gorilla",
      "Bigfoot",
      "Bear"
    ],
    "correct_index": 3,
    "explanation": "Bear is Lava + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0245",
    "prompt": "Which of these animals is NOT a Sky type?",
    "options": [
      "Fairy",
      "Hobbit",
      "Squirrel",
      "Bunyip"
    ],
    "correct_index": 2,
    "explanation": "Squirrel is Fire + Whirlwind — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0246",
    "prompt": "Which of these animals is NOT a Sky type?",
    "options": [
      "Unicorn",
      "Gorilla",
      "Merper",
      "Seamonster"
    ],
    "correct_index": 1,
    "explanation": "Gorilla is Fire + Mountain — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0247",
    "prompt": "Which of these animals is NOT a Fire type?",
    "options": [
      "Panda",
      "Echidna",
      "Gorilla",
      "Seal"
    ],
    "correct_index": 1,
    "explanation": "Echidna is Lava + Lake — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0248",
    "prompt": "Which of these animals is NOT a Fire type?",
    "options": [
      "Otter",
      "Squirrel",
      "Seal",
      "Bear"
    ],
    "correct_index": 3,
    "explanation": "Bear is Lava + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0249",
    "prompt": "Which of these animals is NOT a Tree type?",
    "options": [
      "Giraffe",
      "Snake",
      "Cassowary",
      "Thunderbird"
    ],
    "correct_index": 3,
    "explanation": "Thunderbird is Lightning + Sky — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0250",
    "prompt": "Which of these animals is NOT a Tree type?",
    "options": [
      "Seahorse",
      "Ostrich",
      "Cassowary",
      "Elf"
    ],
    "correct_index": 1,
    "explanation": "Ostrich is Whirlwind + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0251",
    "prompt": "Which of these animals is NOT a Lightning type?",
    "options": [
      "Swordfish",
      "Platypus",
      "Deer",
      "Kingfisher"
    ],
    "correct_index": 3,
    "explanation": "Kingfisher is Sun + River — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0252",
    "prompt": "Which of these animals is NOT a Lightning type?",
    "options": [
      "Thunderbird",
      "Wasp",
      "Bison",
      "Catfish"
    ],
    "correct_index": 2,
    "explanation": "Bison is Mountain + Soil — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0253",
    "prompt": "Which of these animals is NOT a Ocean type?",
    "options": [
      "Dolphin",
      "Octopus",
      "Beaver",
      "Crocodile"
    ],
    "correct_index": 2,
    "explanation": "Beaver is Lake + River — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0254",
    "prompt": "Which of these animals is NOT a Ocean type?",
    "options": [
      "Merper",
      "Octopus",
      "Crocodile",
      "Eel"
    ],
    "correct_index": 3,
    "explanation": "Eel is Lava + River — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0255",
    "prompt": "Which of these animals is NOT a Whirlwind type?",
    "options": [
      "Panda",
      "Woodpecker",
      "Rabbit",
      "Kangaroo"
    ],
    "correct_index": 0,
    "explanation": "Panda is Fire + Lake — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0256",
    "prompt": "Which of these animals is NOT a Whirlwind type?",
    "options": [
      "Rabbit",
      "Bigfoot",
      "Woodpecker",
      "Horse"
    ],
    "correct_index": 1,
    "explanation": "Bigfoot is Mountain + Sky — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0257",
    "prompt": "Which of these animals is NOT a Sun type?",
    "options": [
      "Seamonster",
      "Rainbow Serpent",
      "Lion",
      "Kangaroo"
    ],
    "correct_index": 0,
    "explanation": "Seamonster is River + Sky — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0258",
    "prompt": "Which of these animals is NOT a Sun type?",
    "options": [
      "Turtle",
      "Iguana",
      "Rainbow Serpent",
      "Falcon"
    ],
    "correct_index": 3,
    "explanation": "Falcon is Lightning + Mountain — no overlap with the type asked.",
    "style": "not_animal_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0259",
    "prompt": "Which of these animals carries Snow as one of its Creator types?",
    "options": [
      "Turtle",
      "Swordfish",
      "Swan",
      "Flying Fox"
    ],
    "correct_index": 2,
    "explanation": "Swan is part-Snow.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0260",
    "prompt": "Which of these animals carries Soil as one of its Creator types?",
    "options": [
      "Gorilla",
      "Horse",
      "Hobbit",
      "Stingray"
    ],
    "correct_index": 2,
    "explanation": "Hobbit is part-Soil.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0261",
    "prompt": "Which of these animals carries River as one of its Creator types?",
    "options": [
      "Turtle",
      "Whale",
      "Anteater",
      "Sloth"
    ],
    "correct_index": 2,
    "explanation": "Anteater is part-River.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0262",
    "prompt": "Which of these animals carries Lava as one of its Creator types?",
    "options": [
      "Duck",
      "Rainbow Serpent",
      "Cassowary",
      "Camel"
    ],
    "correct_index": 2,
    "explanation": "Cassowary is part-Lava.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0263",
    "prompt": "Which of these animals carries Lake as one of its Creator types?",
    "options": [
      "Whale",
      "Beaver",
      "Squirrel",
      "Woodpecker"
    ],
    "correct_index": 1,
    "explanation": "Beaver is part-Lake.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0264",
    "prompt": "Which of these animals carries Mountain as one of its Creator types?",
    "options": [
      "Hobbit",
      "Alpaca",
      "Crocodile",
      "Squirrel"
    ],
    "correct_index": 2,
    "explanation": "Crocodile is part-Mountain.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0265",
    "prompt": "Which of these animals carries Sky as one of its Creator types?",
    "options": [
      "Koala",
      "Salamander",
      "Swan",
      "Unicorn"
    ],
    "correct_index": 3,
    "explanation": "Unicorn is part-Sky.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0266",
    "prompt": "Which of these animals carries Fire as one of its Creator types?",
    "options": [
      "Otter",
      "Seamonster",
      "Wasp",
      "Ostrich"
    ],
    "correct_index": 0,
    "explanation": "Otter is part-Fire.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0267",
    "prompt": "Which of these animals carries Tree as one of its Creator types?",
    "options": [
      "Swordfish",
      "Hobbit",
      "Spider",
      "Falcon"
    ],
    "correct_index": 2,
    "explanation": "Spider is part-Tree.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0268",
    "prompt": "Which of these animals carries Lightning as one of its Creator types?",
    "options": [
      "Wasp",
      "Whale",
      "Fox",
      "Camel"
    ],
    "correct_index": 0,
    "explanation": "Wasp is part-Lightning.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0269",
    "prompt": "Which of these animals carries Ocean as one of its Creator types?",
    "options": [
      "Bigfoot",
      "Seamonster",
      "Alpaca",
      "Seal"
    ],
    "correct_index": 3,
    "explanation": "Seal is part-Ocean.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0270",
    "prompt": "Which of these animals carries Whirlwind as one of its Creator types?",
    "options": [
      "Rainbow Serpent",
      "Cheetah",
      "Bison",
      "Woodpecker"
    ],
    "correct_index": 3,
    "explanation": "Woodpecker is part-Whirlwind.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  },
  {
    "id": "q0271",
    "prompt": "Which of these animals carries Sun as one of its Creator types?",
    "options": [
      "Bigfoot",
      "Swordfish",
      "Echidna",
      "Lion"
    ],
    "correct_index": 3,
    "explanation": "Lion is part-Sun.",
    "style": "animal_has_type",
    "category": "animals",
    "creator": null
  }
];
